# Generated by Django 4.2.25 on 2025-10-15 17:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('order_date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.client')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client_payment', 'Client Payment'), ('shop_deposit', 'Shop Deposit')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inputs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Required for CLIENT_PAYMENT type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.order')),
            ],
            options={
                'db_table': 'inputs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_client__2e756d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-order_date'], name='orders_status_648f87_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date', 'client'], name='orders_order_d_fce785_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date', 'status'], name='orders_deliver_cb663b_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('paid_amount__lte', models.F('total_amount'))), name='paid_amount_not_exceed_total'),
        ),
        migrations.AddIndex(
            model_name='input',
            index=models.Index(fields=['-date', 'type'], name='inputs_date_3adc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='input',
            index=models.Index(fields=['order', '-date'], name='inputs_order_i_925855_idx'),
        ),
        migrations.AddIndex(
            model_name='input',
            index=models.Index(fields=['created_by', '-date'], name='inputs_created_d66cb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='input',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order__isnull', False), ('type', 'client_payment')), models.Q(('order__isnull', True), ('type', 'shop_deposit')), _connector='OR'), name='input_client_payment_requires_order'),
        ),
    ]
