# Generated by Django 4.2.25 on 2025-10-20 21:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_orderoutput_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], db_index=True, max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Required when movement_type is OUT (client usage).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='api.product')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'movement_type'], name='stock_movem_date_cedb41_idx'), models.Index(fields=['product', '-date'], name='stock_movem_product_f69112_idx'), models.Index(fields=['order', '-date'], name='stock_movem_order_i_9c2afa_idx')],
            },
        ),
    ]
