# Generated by Django 4.2.25 on 2025-10-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_stockmovement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='output',
            name='output_type_requirements',
        ),
        migrations.RemoveField(
            model_name='output',
            name='Product',
        ),
        migrations.AlterField(
            model_name='output',
            name='order',
            field=models.ForeignKey(blank=True, help_text='(Required for SUPPLIER_PAYMENT and CLIENT_STOCK_USAGE) or optionally for OTHER_EXPENSE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='api.order'),
        ),
        migrations.AlterField(
            model_name='output',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Required for SUPPLIER_PAYMENT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='api.supplier'),
        ),
        migrations.AddField(
            model_name='output',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Required for GLOBAL_STOCK_PURCHASE and CLIENT_STOCK_USAGE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='api.product'),
        ),
    ]
