# Generated by Django 4.2.25 on 2025-10-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_stockmovement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='description',
        ),
    ]
