# Generated by Django 4.2.25 on 2025-10-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_stockmovement_related_order_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by_output',
        ),
        migrations.AddField(
            model_name='orderoutput',
            name='created_by_stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_outputs', to='api.stockmovement'),
        ),
    ]
