# Generated by Django 4.2.25 on 2025-10-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_stockmovement_created_by_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='related_order_output',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='api.output'),
        ),
    ]
