# Generated by Django 4.2.25 on 2025-10-27 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_stockmovement_related_order_output_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='paid_amount_not_exceed_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
