# Generated by Django 4.2.25 on 2025-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedtoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['token'], name='blacklisted_token_d070ae_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['blacklisted_at'], name='blacklisted_blackli_bd04a9_idx'),
        ),
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table='blacklisted_tokens',
        ),
    ]
