# Generated by Django 4.2.25 on 2025-10-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_input_order_orders_client__2e756d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='api.order')),
            ],
            options={
                'db_table': 'order_outputs',
                'ordering': ['-created_at'],
            },
        ),
    ]
