# Generated by Django 4.2.25 on 2025-10-16 08:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('m', 'Meter'), ('m²', 'Square Meter'), ('L', 'Liter'), ('kg', 'Kilogram'), ('g', 'Gram'), ('none', 'Unitless')], db_index=True, default='piece', max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='input',
            name='input_client_payment_requires_order',
        ),
        migrations.RemoveIndex(
            model_name='input',
            name='inputs_date_3adc2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='input',
            name='inputs_order_i_925855_idx',
        ),
        migrations.RemoveIndex(
            model_name='input',
            name='inputs_created_d66cb8_idx',
        ),
        migrations.AlterField(
            model_name='input',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderoutput',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='products_is_acti_1ef63b_idx'),
        ),
    ]
