# Generated by Django 4.2.25 on 2025-10-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_and_more'),
    ]

    operations = [
    ]
