# Generated by Django 4.2.25 on 2025-10-20 18:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderoutput',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='orderoutput',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderoutput',
            name='type',
            field=models.CharField(choices=[('product_consumption', 'Product Consumption'), ('supplier_payment', 'Supplier Payment'), ('other_expense', 'Other Expense')], default='other_expense', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderoutput',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_outputs', to='api.order'),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('supplier_payment', 'Supplier Payment'), ('consumable', 'Consumable'), ('global_stock_purchase', 'Global Stock Purchase'), ('client_stock_usage', 'Client Stock Usage'), ('other_expense', 'Other Expense')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(blank=True, help_text='Required for GLOBAL_STOCK_PURCHASE and CLIENT_STOCK_USAGE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='api.product')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='(Required for SUPPLIER_PAYMENT and CLIENT_STOCK_USAGE) OR OTHER_EXPENSE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='api.order')),
                ('source_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='api.input')),
                ('supplier', models.ForeignKey(blank=True, help_text='Required for SUPPLIER_PAYMENT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='api.supplier')),
            ],
            options={
                'db_table': 'outputs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'type'], name='outputs_date_ade673_idx'), models.Index(fields=['order', '-date'], name='outputs_order_i_a3cb8e_idx'), models.Index(fields=['supplier', '-date'], name='outputs_supplie_2db676_idx'), models.Index(fields=['created_by', '-date'], name='outputs_created_a0ad5e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='output',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order__isnull', False), ('supplier__isnull', False), ('type', 'supplier_payment')), models.Q(('order__isnull', False), ('type', 'client_stock_usage')), models.Q(('type__in', ['supplier_payment', 'client_stock_usage']), _negated=True), _connector='OR'), name='output_type_requirements'),
        ),
    ]
