# Generated by Django 4.2.25 on 2025-10-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_ammount_orderoutput_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoutput',
            name='type',
            field=models.CharField(choices=[('product_consumption', 'Product Consumption'), ('supplier_payment', 'Supplier Payment'), ('other_expense', 'Other Expense')], max_length=30),
        ),
    ]
