# Generated by Django 4.2.25 on 2025-10-21 16:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_output_output_type_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoutput',
            name='created_by_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_outputs', to='api.output'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='api.output'),
        ),
        migrations.AlterField(
            model_name='output',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
