# Generated by Django 4.2.25 on 2025-10-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_product_price_stockmovement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
