# Generated by Django 4.2.25 on 2025-10-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_stockmovement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='related_order_output',
            field=models.ForeignKey(blank=True, help_text='Optional link to the related OrderOutput.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='api.orderoutput'),
        ),
    ]
